[server]
enableCORS = false

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = true

[global]
dataFrameSerialization = "arrow"

[browser]
gatherUsageStats = false

[logger]
level = "info"

[theme]
base="dark" # Changed from "light" to "dark"
primaryColor="#F63366" # This is a bright accent color
backgroundColor="#000000" # Changed to pure black
secondaryBackgroundColor="#1A1A1A" # A dark grey for secondary elements
textColor="#FFFFFF" # White text for contrast
font="sans serif"

# The [main] section and 'command' line should already be REMOVED from here.