[server]
enableCORS = false

[client]
toolbarMode = "minimal"

[runner]
magicEnabled = true

[global]
dataFrameSerialization = "arrow"

[browser]
gatherUsageStats = false

[logger]
level = "info"

[theme]
base="light"
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

# The [main] section and 'command' line are REMOVED from here.